namespace LexiVocab.Application.DTOs.Tag;

public record TagDto(
    Guid Id,
    string Name,
    string? Slug,
    string? Color,
    string? Icon,
    bool IsAutoGenerated,
    string? SourceDomain,
    int DisplayOrder,
    int WordCount,
    DateTime CreatedAt
);

public record CreateTagRequest(
    string Name,
    string? Color,
    string? Icon
);

public record UpdateTagRequest(
    string Name,
    string? Color,
    string? Icon,
    int DisplayOrder
);
