using LexiVocab.Application.Common;
using LexiVocab.Application.Common.Interfaces;
using LexiVocab.Application.DTOs.Tag;
using LexiVocab.Domain.Entities;
using LexiVocab.Domain.Interfaces;
using MediatR;

namespace LexiVocab.Application.Features.Tags.Commands;

public record CreateTagCommand(
    string Name,
    string? Color,
    string? Icon
) : IRequest<Result<TagDto>>;

public class CreateTagHandler : IRequestHandler<CreateTagCommand, Result<TagDto>>
{
    private readonly IUnitOfWork _uow;
    private readonly ICurrentUserService _currentUser;

    public CreateTagHandler(IUnitOfWork uow, ICurrentUserService currentUser)
    {
        _uow = uow;
        _currentUser = currentUser;
    }

    public async Task<Result<TagDto>> Handle(CreateTagCommand request, CancellationToken ct)
    {
        var userId = _currentUser.UserId!.Value;
        
        var entity = new VocabTag
        {
            UserId = userId,
            Name = request.Name.Trim(),
            Slug = request.Name.Trim().ToLowerInvariant().Replace(" ", "-"),
            Color = request.Color ?? "#6366F1",
            Icon = request.Icon ?? "📁"
        };

        await _uow.Tags.AddAsync(entity, ct);
        await _uow.SaveChangesAsync(ct);

        return Result<TagDto>.Created(MapToDto(entity));
    }

    private static TagDto MapToDto(VocabTag t) => new(
        t.Id, t.Name, t.Slug, t.Color, t.Icon, t.IsAutoGenerated, t.SourceDomain, t.DisplayOrder, t.WordCount, t.CreatedAt);
}
