using LexiVocab.Application.Common;
using LexiVocab.Application.Common.Interfaces;
using LexiVocab.Application.DTOs.Tag;
using LexiVocab.Domain.Entities;
using LexiVocab.Domain.Interfaces;
using MediatR;

namespace LexiVocab.Application.Features.Tags.Commands;

// ─── Create Tag ───────────────────────────────────────────────
public record CreateTagCommand(
    string Name,
    string? Color,
    string? Icon
) : IRequest<Result<TagDto>>;

public class CreateTagHandler : IRequestHandler<CreateTagCommand, Result<TagDto>>
{
    private readonly IUnitOfWork _uow;
    private readonly ICurrentUserService _currentUser;

    public CreateTagHandler(IUnitOfWork uow, ICurrentUserService currentUser)
    {
        _uow = uow;
        _currentUser = currentUser;
    }

    public async Task<Result<TagDto>> Handle(CreateTagCommand request, CancellationToken ct)
    {
        var userId = _currentUser.UserId!.Value;
        
        var entity = new VocabTag
        {
            UserId = userId,
            Name = request.Name.Trim(),
            Slug = request.Name.Trim().ToLowerInvariant().Replace(" ", "-"),
            Color = request.Color ?? "#6366F1",
            Icon = request.Icon ?? "📁"
        };

        await _uow.Tags.AddAsync(entity, ct);
        await _uow.SaveChangesAsync(ct);

        return Result<TagDto>.Created(MapToDto(entity));
    }

    private static TagDto MapToDto(VocabTag t) => new(
        t.Id, t.Name, t.Slug, t.Color, t.Icon, t.IsAutoGenerated, t.SourceDomain, t.DisplayOrder, t.WordCount, t.CreatedAt);
}

// ─── Update Tag ───────────────────────────────────────────────
public record UpdateTagCommand(
    Guid Id,
    string Name,
    string? Color,
    string? Icon,
    int DisplayOrder
) : IRequest<Result<TagDto>>;

public class UpdateTagHandler : IRequestHandler<UpdateTagCommand, Result<TagDto>>
{
    private readonly IUnitOfWork _uow;
    private readonly ICurrentUserService _currentUser;

    public UpdateTagHandler(IUnitOfWork uow, ICurrentUserService currentUser)
    {
        _uow = uow;
        _currentUser = currentUser;
    }

    public async Task<Result<TagDto>> Handle(UpdateTagCommand request, CancellationToken ct)
    {
        var entity = await _uow.Tags.GetByIdAsync(request.Id, ct);
        if (entity is null || entity.UserId != _currentUser.UserId)
            return Result<TagDto>.NotFound("Tag not found.");

        entity.Name = request.Name.Trim();
        entity.Slug = request.Name.Trim().ToLowerInvariant().Replace(" ", "-");
        entity.Color = request.Color;
        entity.Icon = request.Icon;
        entity.DisplayOrder = request.DisplayOrder;
        entity.UpdatedAt = DateTime.UtcNow;

        _uow.Tags.Update(entity);
        await _uow.SaveChangesAsync(ct);

        return Result<TagDto>.Success(new TagDto(
            entity.Id, entity.Name, entity.Slug, entity.Color, 
            entity.Icon, entity.IsAutoGenerated, entity.SourceDomain, 
            entity.DisplayOrder, entity.WordCount, entity.CreatedAt));
    }
}

// ─── Delete Tag ───────────────────────────────────────────────
public record DeleteTagCommand(Guid Id) : IRequest<Result>;

public class DeleteTagHandler : IRequestHandler<DeleteTagCommand, Result>
{
    private readonly IUnitOfWork _uow;
    private readonly ICurrentUserService _currentUser;

    public DeleteTagHandler(IUnitOfWork uow, ICurrentUserService currentUser)
    {
        _uow = uow;
        _currentUser = currentUser;
    }

    public async Task<Result> Handle(DeleteTagCommand request, CancellationToken ct)
    {
        var entity = await _uow.Tags.GetByIdAsync(request.Id, ct);
        if (entity is null || entity.UserId != _currentUser.UserId)
            return Result.NotFound("Tag not found.");

        // Uncategorize vocabularies is handled by EF Core SetNull ON DELETE behaviour for TagId
        _uow.Tags.Remove(entity);
        await _uow.SaveChangesAsync(ct);

        return Result.Success();
    }
}

// ─── Assign Vocab To Tag ─────────────────────────────────────────
public record AssignVocabToTagCommand(Guid TagId, Guid VocabularyId) : IRequest<Result>;

public class AssignVocabToTagHandler : IRequestHandler<AssignVocabToTagCommand, Result>
{
    private readonly IUnitOfWork _uow;
    private readonly ICurrentUserService _currentUser;

    public AssignVocabToTagHandler(IUnitOfWork uow, ICurrentUserService currentUser)
    {
        _uow = uow;
        _currentUser = currentUser;
    }

    public async Task<Result> Handle(AssignVocabToTagCommand request, CancellationToken ct)
    {
        var vocab = await _uow.Vocabularies.GetByIdAsync(request.VocabularyId, ct);
        if (vocab is null || vocab.UserId != _currentUser.UserId)
            return Result.NotFound("Vocabulary not found.");
            
        var tag = await _uow.Tags.GetByIdAsync(request.TagId, ct);
        if (tag is null || tag.UserId != _currentUser.UserId)
            return Result.NotFound("Tag not found.");

        vocab.TagId = request.TagId;
        _uow.Vocabularies.Update(vocab);
        await _uow.SaveChangesAsync(ct);

        return Result.Success();
    }
}
