using LexiVocab.Application.Common;
using LexiVocab.Application.Common.Interfaces;
using LexiVocab.Application.DTOs.Tag;
using LexiVocab.Domain.Interfaces;
using MediatR;

namespace LexiVocab.Application.Features.Tags.Commands;

public record UpdateTagCommand(
    Guid Id,
    string Name,
    string? Color,
    string? Icon,
    int DisplayOrder
) : IRequest<Result<TagDto>>;

public class UpdateTagHandler : IRequestHandler<UpdateTagCommand, Result<TagDto>>
{
    private readonly IUnitOfWork _uow;
    private readonly ICurrentUserService _currentUser;

    public UpdateTagHandler(IUnitOfWork uow, ICurrentUserService currentUser)
    {
        _uow = uow;
        _currentUser = currentUser;
    }

    public async Task<Result<TagDto>> Handle(UpdateTagCommand request, CancellationToken ct)
    {
        var entity = await _uow.Tags.GetByIdAsync(request.Id, ct);
        if (entity is null || entity.UserId != _currentUser.UserId)
            return Result<TagDto>.NotFound("Tag not found.");

        entity.Name = request.Name.Trim();
        entity.Slug = request.Name.Trim().ToLowerInvariant().Replace(" ", "-");
        entity.Color = request.Color;
        entity.Icon = request.Icon;
        entity.DisplayOrder = request.DisplayOrder;
        entity.UpdatedAt = DateTime.UtcNow;

        _uow.Tags.Update(entity);
        await _uow.SaveChangesAsync(ct);

        return Result<TagDto>.Success(new TagDto(
            entity.Id, entity.Name, entity.Slug, entity.Color, 
            entity.Icon, entity.IsAutoGenerated, entity.SourceDomain, 
            entity.DisplayOrder, entity.WordCount, entity.CreatedAt));
    }
}
