using LexiVocab.Domain.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace LexiVocab.Infrastructure.Persistence.Configurations;

public class VocabTagConfiguration : IEntityTypeConfiguration<VocabTag>
{
    public void Configure(EntityTypeBuilder<VocabTag> builder)
    {
        builder.ToTable("vocab_tags");

        builder.HasKey(t => t.Id);
        builder.Property(t => t.Id).HasColumnName("id");

        builder.Property(t => t.UserId).HasColumnName("user_id").IsRequired();

        builder.Property(t => t.Name)
            .HasColumnName("name")
            .HasMaxLength(100)
            .IsRequired();

        builder.Property(t => t.Slug)
            .HasColumnName("slug")
            .HasMaxLength(120);

        builder.Property(t => t.Color)
            .HasColumnName("color")
            .HasMaxLength(20)
            .HasDefaultValue("#6366F1");

        builder.Property(t => t.Icon)
            .HasColumnName("icon")
            .HasMaxLength(20)
            .HasDefaultValue("📁");

        builder.Property(t => t.IsAutoGenerated)
            .HasColumnName("is_auto_generated")
            .HasDefaultValue(false);

        builder.Property(t => t.SourceDomain)
            .HasColumnName("source_domain")
            .HasMaxLength(255);

        builder.Property(t => t.DisplayOrder)
            .HasColumnName("display_order")
            .HasDefaultValue(0);

        builder.Property(t => t.WordCount)
            .HasColumnName("word_count")
            .HasDefaultValue(0);

        builder.Property(t => t.CreatedAt)
            .HasColumnName("created_at")
            .HasDefaultValueSql("NOW()");

        builder.Property(t => t.UpdatedAt).HasColumnName("updated_at");

        // Indexes
        builder.HasIndex(t => t.UserId).HasDatabaseName("ix_vocab_tags_user_id");
        builder.HasIndex(t => new { t.UserId, t.Slug })
            .IsUnique()
            .HasDatabaseName("ix_vocab_tags_user_slug");

        // Relationships are configured in dependent entities (User, UserVocabulary)
    }
}
