using LexiVocab.Domain.Common;

namespace LexiVocab.Domain.Entities;

/// <summary>
/// A category or tag for grouping vocabularies.
/// Can be user-created or auto-generated based on source domain.
/// </summary>
public class VocabTag : BaseEntity
{
    public Guid UserId { get; set; }

    /// <summary>Display name (e.g., "IELTS Writing", "Daily Life")</summary>
    public string Name { get; set; } = string.Empty;

    /// <summary>URL-friendly identifier</summary>
    public string? Slug { get; set; }

    /// <summary>Highlight color in hex format</summary>
    public string? Color { get; set; } = "#6366F1";

    /// <summary>Emoji icon for visual distinction</summary>
    public string? Icon { get; set; } = "🏷️";

    /// <summary>If true, this was automatically created from a website</summary>
    public bool IsAutoGenerated { get; set; }

    /// <summary>The original domain if auto-generated (e.g., bbc.com)</summary>
    public string? SourceDomain { get; set; }

    /// <summary>Ordering on dashboard</summary>
    public int DisplayOrder { get; set; }

    /// <summary>Denormalized total vocabularies in this tag</summary>
    public int WordCount { get; set; }

    // Navigation properties
    public User User { get; set; } = null!;
    public ICollection<UserVocabulary> UserVocabularies { get; set; } = [];
}
