using LexiVocab.Application.Common;
using LexiVocab.Application.Common.Interfaces;
using LexiVocab.Application.DTOs.Tag;
using LexiVocab.Domain.Interfaces;
using MediatR;

namespace LexiVocab.Application.Features.Tags.Queries;

public record GetTagListQuery() : IRequest<Result<IEnumerable<TagDto>>>;

public class GetTagListHandler : IRequestHandler<GetTagListQuery, Result<IEnumerable<TagDto>>>
{
    private readonly IUnitOfWork _uow;
    private readonly ICurrentUserService _currentUser;

    public GetTagListHandler(IUnitOfWork uow, ICurrentUserService currentUser)
    {
        _uow = uow;
        _currentUser = currentUser;
    }

    public async Task<Result<IEnumerable<TagDto>>> Handle(GetTagListQuery request, CancellationToken ct)
    {
        var userId = _currentUser.UserId!.Value;
        var tags = await _uow.Tags.GetByUserIdAsync(userId, ct);

        var dtos = tags.Select(t => new TagDto(
            t.Id, t.Name, t.Slug, t.Color, t.Icon, 
            t.IsAutoGenerated, t.SourceDomain, 
            t.DisplayOrder, t.WordCount, t.CreatedAt
        ));

        return Result<IEnumerable<TagDto>>.Success(dtos);
    }
}
