using LexiVocab.Domain.Entities;
using LexiVocab.Domain.Interfaces;
using LexiVocab.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;

namespace LexiVocab.Infrastructure.Repositories;

public class VocabTagRepository : GenericRepository<VocabTag>, IVocabTagRepository
{
    public VocabTagRepository(AppDbContext dbContext) : base(dbContext)
    {
    }

    public async Task<IEnumerable<VocabTag>> GetByUserIdAsync(Guid userId, CancellationToken ct = default)
    {
        return await _dbSet
            .Where(t => t.UserId == userId)
            .OrderBy(t => t.DisplayOrder)
            .ThenByDescending(t => t.WordCount)
            .ToListAsync(ct);
    }

    public async Task<VocabTag?> GetBySlugAsync(Guid userId, string slug, CancellationToken ct = default)
    {
        return await _dbSet
            .FirstOrDefaultAsync(t => t.UserId == userId && t.Slug == slug, ct);
    }

    public async Task<VocabTag> GetOrCreateByDomainAsync(Guid userId, string domain, CancellationToken ct = default)
    {
        var slug = domain.ToLowerInvariant().Replace(".", "-");
        var existing = await GetBySlugAsync(userId, slug, ct);

        if (existing is null)
        {
            var newTag = new VocabTag
            {
                UserId = userId,
                Name = domain,
                Slug = slug,
                Color = "#94A3B8", // default slate color for auto-generated
                Icon = "🌐",
                IsAutoGenerated = true,
                SourceDomain = domain,
                WordCount = 0
            };

            await AddAsync(newTag, ct);
            return newTag;
        }

        return existing;
    }
}
